### PR TITLE
Fixes linting errors (bad minSdkVersion and cursor.getColumnIndex returning negative value)

### LINKED ISSUE #851: Lint found errors in the project; aborting build.
**Platform**
- [x] Android
- [] iOS
- [] Web
- [] Desktop (Go)

```
$ android/gradlew clean
$ android/gradlew build

> Task :file_picker:lint FAILED
Ran lint on variant debug: 9 issues found
Ran lint on variant release: 9 issues found
Ran lint on variant profile: 9 issues found
Wrote HTML report to file:///home/kevin/git_projects/flutter_assets/build/file_picker/reports/lint-results.html
Wrote XML report to file:///home/kevin/git_projects/flutter_assets/build/file_picker/reports/lint-results.xml
w: Detected multiple Kotlin daemon sessions at ../build/kotlin/sessions

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':file_picker:lint'.
> Lint found errors in the project; aborting build.
  
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...
  Errors found:
  
  /home/user1/.pub-cache/hosted/pub.dartlang.org/file_picker-4.1.4/android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java:188: Error: Call requires API level 19 (current min is 16): android.provider.DocumentsContract#getDocumentId [NewApi]
                  String docId = DocumentsContract.getDocumentId(treeUri);
                                                   ~~~~~~~~~~~~~
  /home/user1/.pub-cache/hosted/pub.dartlang.org/file_picker-4.1.4/android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java:66: Error: Value must be ≥ 0 [Range]
                          result = cursor.getString(cursor.getColumnIndex(OpenableColumns.DISPLAY_NAME));
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by AngeloAvv**
* Raised up minSdkVersion to 19 since FileUtils uses DocumentsContract.getDocumentId(android.net.Uri) (officially available since API 19)

* Fixed getColumnIndex which may return a negative integer
* Fixed example package names due to a missing dot typo

Fixes #851

### CODE REVIEW

**Comment by miguelpruivo** [comment]
I’m afraid that it could introduce breaking changes for those still supporting API 16.

**Comment by AngeloAvv** [comment]
How could people use API 16 if you are invoking a method that does not exist for people using Android lower than 19?

This library should be broken for API 16 to 18.

**Comment by miguelpruivo** [comment]
If min version is API 16 and builds it’s because it works. You can give it a try by setting up a simulator and building for SDK 16.

**Comment by AngeloAvv** [comment]
If you open your project in Android Studio you will figure out that the linter is reporting an error on this line:
`                String docId = DocumentsContract.getDocumentId(treeUri);
`

That's because `DocumentsContract` class exists starting from API 19 as reported [here](https://developer.android.com/reference/android/provider/DocumentsContract)

The linter is reporting the error because you are targeting this library for API 16 and above, but you can't invoke that method since according to the linter that class does not exist. 

How could you say it builds if the linter fails? As I said, you can simply see the error by opening your project with Android Studio or by running the gradle task `lint` (or `lintDebug`/`lintRelease`)



```
> Task :file_picker:lintDebug FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':file_picker:lintDebug'.
> Lint found errors in the project; aborting build.
  
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...
  Errors found:
  
  /root/.pub-cache/hosted/pub.dartlang.org/file_picker-4.2.4/android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java:189: Error: Call requires API level 19 (current min is 16): android.provider.DocumentsContract#getDocumentId [NewApi]
                  String docId = DocumentsContract.getDocumentId(treeUri);
                                                   ~~~~~~~~~~~~~
  
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings
BUILD FAILED in 8m 22s
330 actionable tasks: 330 executed
```

```
> Task :file_picker:lintRelease FAILED
Wrote HTML report to file:///root/.pub-cache/hosted/pub.dartlang.org/file_picker-4.2.4/android/build/reports/lint-results-release.html
Wrote XML report to file:///root/.pub-cache/hosted/pub.dartlang.org/file_picker-4.2.4/android/build/reports/lint-results-release.xml
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':file_picker:lintRelease'.
> Lint found errors in the project; aborting build.
  
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...
  Errors found:
  
  /root/.pub-cache/hosted/pub.dartlang.org/file_picker-4.2.4/android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java:189: Error: Call requires API level 19 (current min is 16): android.provider.DocumentsContract#getDocumentId [NewApi]
                  String docId = DocumentsContract.getDocumentId(treeUri);
                                                   ~~~~~~~~~~~~~
  
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings
BUILD FAILED in 8m 28s
330 actionable tasks: 330 executed
```

**Comment by AngeloAvv** [comment]
@miguelpruivo I studied a little bit more the library and I understood that this method
`DocumentsContract.getDocumentId`
should only be invoked when picking a folder, which is only available in Android starting from API 21 according to your documentation (I'm not able to launch "Pick Folder" in your example in Android 16 so I cannot follow the flow of the method written above), so it should be safe to annotate the method
`getFullPathFromTreeUri` with TargetAPI 21. 

Can you confirm this? If so, we can still target API 16 as minSdkVersion and definitely shut down the linter error

**Comment by miguelpruivo** [comment]
That’s correct.

**Comment by AngeloAvv** [comment]
@miguelpruivo done and added to the merge request, thanks.

**Comment by miguelpruivo** [comment]
Please update version and changelog. Thanks.

**Comment by AngeloAvv** [comment]
Done, hope everything is ok.

**Review by miguelpruivo — APPROVED** [review]

**Pull request merged**
