### PR TITLE
[Android] remove unnecessary external storage permission 

### PR DESCRIPTION
**Pull request by Pluxury**
In this PR, I have removed everything related to the request for access to external storage. Permission is not required for the plugin to work correctly on android.
This was also discussed in https://github.com/miguelpruivo/flutter_file_picker/issues/872

I have tested it on several emulators from API 27 to API 33

P.S I'm sorry, I accidentally deleted the previous PR that was [here](https://github.com/miguelpruivo/flutter_file_picker/pull/1444)

### CODE REVIEW

**Comment by Liloupar** [comment]
Great job! Removing unnecessary privacy permissions is definitely user-friendly. @miguelpruivo , could you take a look at this pull request?

**Review by miguelpruivo — APPROVED** [review]
LGTM.

**Comment by miguelpruivo** [comment]
@Pluxury have you tested in older SDKs such as 21?

**Comment by Pluxury** [comment]
> @Pluxury before merging, have you tested in older SDKs such as 21?

Unfortunately, no. There is no way to do this now, but judging by the documentation, there should be no problems

**Comment by Liloupar** [comment]
Can this pull request be merged? @miguelpruivo 
thanks

**Comment by miguelpruivo** [comment]
Can you please resolve the conflicts?

**Comment by syleishere** [comment]
https://developer.android.com/about/versions/14/changes/partial-photo-video-access

**Comment by miguelpruivo** [comment]
LGTM. Thanks.

**Comment by millerf** [comment]
This introduced an error when buyilding for android:

```
/Users/millerf/.pub-cache/hosted/pub.dev/file_picker-8.1.5/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:257: error: cannot find symbol
        if (registrar != null) {
            ^
  symbol:   variable registrar
  location: class FilePickerPlugin
/Users/millerf/.pub-cache/hosted/pub.dev/file_picker-8.1.5/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:260: error: cannot find symbol
            registrar.addActivityResultListener(this.delegate);
            ^
  symbol:   variable registrar
  location: class FilePickerPlugin
2 errors

FAILURE: Build failed with an exception.


```

With gradle-7.5-all.zip and

```
 compileSdkVersion = 34                // or higher / as desired
        targetSdkVersion = 34                // or higher / as desired
        minSdkVersion = 23                // Required minimum
        appCompatVersion = "1.4.2"           // or higher / as desired
        playServicesLocationVersion = "21.0.1"  // or higher / as de
```

**Comment by MrCsabaToth** [comment]
This PR added back V1 embedding which now causes problem.

**Pull request merged**
