### PR TITLE
adding support for the “m4a” format

### PR DESCRIPTION
**Pull request by siyangstar**
adding support for the “m4a” format

### CODE REVIEW

**Comment by navaronbracke** [comment]
What about support on other platforms?

**Comment by siyangstar** [comment]
> What about support on other platforms?

Thank you for your feedback. Regarding the .m4a support on other platforms:

Android: .m4a files are natively supported on Android (4.1 and above), and should work well with file_picker. However, I will perform additional testing to ensure seamless integration.

iOS: Since .m4a is part of Apple’s AAC format, it’s natively supported on iOS devices. This format is commonly used and works reliably with iOS apps.

Windows: .m4a files are generally supported on Windows 10 and above due to built-in media capabilities. I will verify if file_picker handles .m4a correctly on Windows.

macOS: Native support for .m4a is excellent on macOS, with Finder and Quick Look providing easy access and playback. I will confirm compatibility with the plugin.

Web: Modern browsers like Chrome, Firefox, Safari, and Edge all support .m4a playback. I will ensure file_picker correctly handles these files in web applications.

**Comment by siyangstar** [comment]
Additionally, for Linux, .m4a files are generally supported by most modern distributions, especially when the necessary codecs (like those from GStreamer or FFmpeg) are installed.

**Review by stephane-archer — APPROVED** [review]

**Comment by miguelpruivo** [comment]
Will be added in the next version. Thanks.

**Pull request merged**
