### PR TITLE
Fix crashing on iOS with getDirectoryPath()

### LINKED ISSUE #1345: Crashing on iOS with getDirectoryPath()
**Describe the bug**
Crashing when picking a directory path `FilePicker.platform.getDirectoryPath()`

**Platform**

- [ ] Android
- [x] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
iPhone 7, iOS 15.7.2

**How are you picking?**
Snippet code from [example](https://github.com/miguelpruivo/flutter_file_picker/tree/master/example) project
```
String? path = await FilePicker.platform.getDirectoryPath(
  dialogTitle: _dialogTitleController.text,
  initialDirectory: _initialDirectoryController.text,
  lockParentWindow: _lockParentWindow,
);
```

**Details to reproduce the issue**
1. Run the [example](https://github.com/miguelpruivo/flutter_file_picker/tree/master/example) in this plugin
2. Click on `Pick folder` button
3. Select one folder in `On My iPhone` menu section > Done
4. App crash with below trace log

**Error Log**
```console
Connecting to VM Service at ws://127.0.0.1:62594/IpigRfWW35c=/ws
“Share files” couldn’t be moved because you don’t have permission to access “tmp”.
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'
*** First throw call stack:
(0x180d7fc80 0x1985a3ee4 0x180e7a6b4 0x180d19f6c 0x10026cb80 0x1839b33a8 0x1833acca8 0x1838b899c 0x183252d8c 0x1834510ec 0x1832b8518 0x1841dc428 0x1832d24e4 0x1831a6cf0 0x1831ba6b8 0x1831ba80c 0x1848a8730 0x180a40094 0x1809ecd44 0x1809ec994 0x180d3b034 0x180cf8538 0x180d0b194 0x1a183e988 0x18350da88 0x1832a6fc8 0x100117798 0x1006344d0)
libc++abi: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001bb654bbc libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`:
->  0x1bb654bbc <+8>:  b.lo   0x1bb654bd8               ; <+36>
    0x1bb654bc0 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1bb654bc4 <+16>: mov    x29, sp
    0x1bb654bc8 <+20>: bl     0x1bb65060c               ; cerror_nocancel
Target 0: (Runner) stopped.
Lost connection to device.
Exited
```

**Flutter Version details**
<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5 22G74 darwin-x64, locale en-VN)
    • Flutter version 3.10.6 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (3 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 15A5195m
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 115.0.5790.114

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

### PR DESCRIPTION
**Pull request by huynguyennovem**
Fix #1345

https://github.com/miguelpruivo/flutter_file_picker/assets/29337364/836d1613-4f63-42f3-b38f-6afba4f85616

### CODE REVIEW

**Comment by miguelpruivo** [comment]
Is this still an issue with iOS 17? Could you please check if there are any changes and also update the changelog/pubspec patch version?

Thanks.

**Review by miguelpruivo — CHANGES_REQUESTED** [review]
Is this still an issue with iOS 17? Could you please check if there are any changes and also update the changelog/pubspec patch version?

Thanks.

**Comment by tomekit** [comment]
This addressed the crash issue on my end, tested on iPhone 8 (16.4), however after I get the folder path and try to list files inside I get: "PathNotFoundException: Directory listing failed". 
Are there any additional permission requests that needs to be done prior to calling dir listing?

**Comment by huynguyennovem** [comment]
I checked on iPhone 5 Pro, iOS 17.0 but the crash didn't occur there. Perhaps this's an OS-specific issue only.

**Pull request closed without merging**
