### PR TITLE
Fix NullPointerException in tearDown()

### PR DESCRIPTION
**Pull request by josephx86**

### CODE REVIEW

**Comment by josephx86** [comment]
When starting an app, the UI hangs when tearDown() crashes. I checked the event logs.

**Comment by josephx86** [comment]
I used jadx and information from logs to pinpoint the line causing the crash

**Comment by miguelpruivo** [comment]
Do you have the logs? It's weird because it shouldn't ever be `null`.

**Comment by josephx86** [comment]
that is what I thought too. It should never be null but the logs are showing it is. I have screenshots.

**Comment by josephx86** [comment]
.... and from jadx

**Comment by miguelpruivo** [comment]
Does that happen on multiple devices?

**Comment by josephx86** [comment]
The problem only happens when an app is installed from the Play Store in my case, so that is why I ended up tracking this issue hacky way reversing an apk.

I have this issue on a Galaxy Note9, Nexus 5X, and a Blu Advance 5.2 (A290Q)

**Comment by miguelpruivo** [comment]
@josephx86 which Flutter version were used to build that release?

**Comment by josephx86** [comment]
I tested with both stable and dev last week. At the moment is am using dev 1.20.0-1.0.pre

**Comment by miguelpruivo** [comment]
@josephx86 can you try with latest 1.12.0 running on Flutter stable and let me know if you are still experiencing the same issue? Thanks.

**Comment by vlefort** [comment]
I i'm also facing the same issue.
image

All work on emulator but not when my user use the Play store App...

I was with flutter dev channel, I try to use flutter stable channel (1.20.4) and give use a feedback when published.

**Comment by miguelpruivo** [comment]
@vlefort does that happen with latest version (2.0.0)?

**Comment by vlefort** [comment]
Stangely it looks the same. 
image.

Flutter 1.20.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fba99f6cf9 (3 days ago) • 2020-09-14 15:32:52 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2

  file_picker: ^2.0.0

**Comment by miguelpruivo** [comment]
I'll eventually merge this, however, with the uncertain of what might be causing it. It shouldn't be `null` at that point.

**Review by miguelpruivo — APPROVED** [review]

**Comment by miguelpruivo** [comment]
Fix added. Closing.

**Pull request closed without merging**
