### PR TITLE
fix: go-flutter channel name

### PR DESCRIPTION
**Pull request by geoah**

### CODE REVIEW

**Comment by geoah** [comment]
oops. sorry this was meant to be opened on my fork for now. :D

**Comment by miguelpruivo** [comment]
No problem, good catch, will immediately fix @geoah.

**Comment by geoah** [comment]
@miguelpruivo sorry wanted to first test it :)
Seems to work after this.

**Comment by geoah** [comment]
Closed as of https://github.com/miguelpruivo/flutter_file_picker/commit/e35b6aae601f1ffd9ba52a30d1c8c4e8ac25e92e

**Pull request closed without merging**
