### PR TITLE
Add support for Safari mobile and fix bugs

### PR DESCRIPTION
**Pull request by AleksMx**
Add support for Safari mobile and fix bugs

1. Add input element on the page
2. Call addEventListener to register change event in the Safari
3. Use separate FileReader objects to process each file
4. Do not use readAsDataUrl to read file (for performance reasons). Changed to readAsArrayBuffer.
5. Call readAsArrayBuffer when withData == true and call readAsDataUrl when withData == false
6. Using the correct filename
7. Do not pass the path to the file, as browsers replace it with a fake one

### CODE REVIEW

**Comment by miguelpruivo** [comment]
@AleksMx thank you, could you please rebase to master first?

**Comment by AleksMx** [comment]
> @AleksMx thank you, could you please rebase to master first?
I do not understand how to do this. In my fork my commits already in the master branch..

**Comment by miguelpruivo** [comment]
@AleksMx don’t worry. I’ll take a look into it in a few days. Thank you!

**Comment by AleksMx** [comment]
> @AleksMx don’t worry. I’ll take a look into it in a few days. Thank you!

When can we merge the request?

**Comment by miguelpruivo** [comment]
@AleksMx sorry I’ve been busy with iOS 14 updates but I’ll take care of this today.

**Comment by miguelpruivo** [comment]
@AleksMx this is now merged and added to 2.0.2.

Thank you!

**Pull request closed without merging**
