### PR TITLE
fix #1335: fix intent flag from ACTION_GET_CONTENT to ACTION_OPEN_DOCUMENT

### LINKED ISSUE #1335: FileType.custom and FileType.custom doesn't work on Android 14
**Describe the bug**

On Android 14, I tried to pick files using `type: FileType.custom` and `type: FileType.any` but it didn't work well.

**Platform**

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**How are you picking?**
```
final result = await FilePicker.platform.pickFiles(
  type: FileType.custom,
  allowedExtensions: [
    'jpg',
    'jpeg',
    'png',
    'pdf',
    'txt',
    'doc',
    'docx',
    'xml',
    'xls',
    'xlsx',
    'ppt',
    'pptx',
  ],
  withData: true,
);
```

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.

```
[!] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-x64, locale ja-JP)
    • Flutter version 3.10.5 on channel stable at /Users/user/fvm/versions/3.10.5
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/2.18.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/user/fvm/versions/3.10.5. Consider adding /Users/user/fvm/versions/3.10.5/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (7 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.4.1 22F82 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 115.0.5790.114

[✓] Network resources
    • All expected network resources are available.
```

**How to solve this issue**

I downloaded this package on my Project, and changed `FilePickerDelegate.javaL236`.

From: `intent = new Intent(Intent.ACTION_GET_CONTENT);`
To: `intent = new Intent(Intent.ACTION_OPEN_DOCUMENT);`

Would you mind if I create a PR for this issue ?

### PR DESCRIPTION
**Pull request by muttsu-623**
fix #1335: fix intent flag from ACTION_GET_CONTENT to ACTION_OPEN_DOCUMENT

### CODE REVIEW

**Comment by muttsu-623** [comment]
@miguelpruivo 
Hi @miguelpruivo , I hope you're doing well!
I've created a Pull Request and would love to hear your thoughts and suggestions 😄

**Comment by miguelpruivo** [comment]
Hi, what were the reason behind this change?

**Comment by julian-CStack** [comment]
> Hi, what were the reason behind this change?

My guess would be the `FilePickerResult` returned from `pickFiles()` being null. At least this is what is happening in my case.

https://github.com/miguelpruivo/flutter_file_picker/issues/1335#issuecomment-1714659456

**Comment by melWiss** [comment]
ping on this

**Comment by daviresio** [comment]
ping on this

**Comment by muttsu-623** [comment]
@miguelpruivo 
Is there any problem?

**Comment by miguelpruivo** [comment]
I'm afraid to merge this change because I believe it could introduce breaking changes for a lot of users. I don't see a lot of traction on this issue, and if this was the case (for most) that would mean that a lot of devs would be pinging on this. 

On the other hand, I'm not sure if changing to OPEN_DOCUMENT will introduce more issues than solve, because we are actually getting (GET_CONTENT) here to get the raw files, not opening. The OPEN_DOCUMENT is more intended to launch the file, rather than manipulating its data from what I understood.

**Comment by BitBlueDevStudio** [comment]
@miguelpruivo what about making this optional, to use Intent.ACTION_OPEN_DOCUMENT or Intent.ACTION_GET_CONTENT?

**Comment by dmitrio95** [comment]
This PR seems to introduce changes similar to #1380 so I'll mention it here too: it seems that this change breaks file picker on some older Android versions, at least on Android 9. https://github.com/miguelpruivo/flutter_file_picker/pull/1380#discussion_r1485321475

**Comment by miguelpruivo** [comment]
Dup of #1380.

**Comment by sneurlax** [comment]
@miguelpruivo, this doesn't seem to be a duplicate of #1380: #1380 has more changes.  Are they consequential?

We have had to use muttsu-623's flutter_file_picker for Android because of this issue, but muttsu-623's fork has Windows issues.  So today I forked this and made cypherstack/flutter_file_picker which is your 8.0.3 + muttsu-623's single change: https://github.com/muttsu-623/flutter_file_picker/commit/f0930d9fa79d347b2a0e25a7de4f5a4a88a9a907

This PR should be merged.  Does it need changes?

**Pull request closed without merging**
