### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by uSlashVlad**
I have an issue with library because I want to use `ffi` version >= 2.0.0, but file picker requires `ffi` < 2.0.0

So I updated all the dependencies. Because I changed to `lints` 2.0.0, I fixed problems a bit

Tests are passed:

- file_picker_macos_test.dart
- file_picker_utils_test.dart

Can't process windows and linux tests because I ran it on MacOS machine

### CODE REVIEW

**Review by h4j4x — APPROVED** [review]
Tests passed ok on Kubuntu 22 (flutter 3.0.5).
Used on a working project as direct dependency: 
```
file_picker:
    git:
      url: git@github.com:uSlashVlad/flutter_file_picker.git
```
It works ok.
Needed to use with plugin "package_info_plus: ^1.4.3"

**Comment by sergmister** [comment]
This should definitely be implemented soon.

**Comment by MrCsabaToth** [comment]
Fixes #1071 ?

**Review by MrCsabaToth — APPROVED** [review]
I haven't tested this with Windows, but the code makes several changes along some common linter reported issues.

**Review by princeteck — APPROVED** [review]
Tested on windows 10 with following 
```
->flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1826], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.69.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!
```

Result: 
```
Working Fine
```

image

**Comment by miguelpruivo** [comment]
Please, update the CHANGELOG and bump fix version @uSlashVlad.

**Review by miguelpruivo — CHANGES_REQUESTED** [review]
Please, update the CHANGELOG and bump fix version @uSlashVlad.

**Comment by uSlashVlad** [comment]
I fixed the issue that managed my branch to fail (it was issued by `path: ^1.8.1`). Also I bumped version to 5.0.0 since ffi >=2.0.0 depends on Dart SDK >= 2.17.0 and this package should also depend on SDK >= 2.17.0. Added information about updating dependencies to CHANGELOG

Utils and MacOS tests are passed

**Review by princeteck — APPROVED** [review]
Looks good!

**Review by miguelpruivo — APPROVED** [review]

**Comment by uSlashVlad** [comment]
Looks like CI is failed because it has flutter 2.x

**Comment by uSlashVlad** [comment]
Should I change flutter version in CI pipeline for my branch?

**Comment by miguelpruivo** [comment]
> Should I change flutter version in CI pipeline for my branch?

If you don't mind, that'd be great! Thank you.

**Comment by holdenhinkle** [comment]
Thank you!

**Pull request merged**
