### PR TITLE
Image picking fail issue solved for live images on newer IOS.

### PR DESCRIPTION
**Pull request by nagibazad**
I have separated the metadata first then append it with the image then saved it to a temporary directory.

### CODE REVIEW

**Review by mustafiz012 — COMMENTED** [review]
I was facing the metadata missing issue badly for **iPhone live photos**. I have tried multiple live images captured by **iPhone 12 (iOS 15.6.1)**, which perfectly works for me. Thanks a ton, @nagibazad for the fix.

**Review by miguelpruivo — APPROVED** [review]

**Comment by miguelpruivo** [comment]
Thank you.

**Comment by doc-rj-ebay** [comment]
@nagibazad @mustafiz012 What was the symptom of this issue, and what iOS versions were impacted? Was this causing a crash? Thanks for any info, I'm trying to correlate with issues we have seen.

**Comment by mustafiz012** [comment]
@doc-rj-ebay  iOS 15+ were affected.

**Pull request merged**
