### PR TITLE
Save file to mobile platforms.

### PR DESCRIPTION
**Pull request by Samoy**
User can save file to mobile platforms with bytes. Desktop platforms remain unchanged.

### CODE REVIEW

**Review by miguelpruivo — CHANGES_REQUESTED** [review]
Thank you. Looks good. Can you please update the major version and changelog accordingly?

**Comment by loloof64** [comment]
Hi ! Is there a chance that this pull request will be merged soon ?

**Comment by loloof64** [comment]
Hi ! Is there a way I can help, even if I'm still an intermediate Flutter & Dart developper ?

**Review by miguelpruivo — APPROVED** [review]
LGTM.

**Comment by miguelpruivo** [comment]
@Samoy there are just a few imports conflicts, could you please address it so I can merge?

Thanks.

**Comment by Samoy** [comment]
@miguelpruivo OK


> @Samoy there are just a few imports conflicts, could you please address it so I can merge?
> 
> Thanks.

Ok, it has been resolved.

**Comment by miguelpruivo** [comment]
Merged, thanks! It'll be available in the 7.1.0.

**Pull request merged**
