### PR TITLE
Fix getDirectoryPath()

### LINKED ISSUE #745: getDirectoryPath() doesn't work in example app on Android 11 (OnePlus)
**Describe the bug**
- Run the example app with `flutter run --release` on Android 11 (OnePlus in my case)
- Try to pick a directory using the "Pick folder" button in the example app
-> Always returns an empty path (`/`) even for unprotected directories

**When changing the `targetSdkVersion` to `29` in `example/android/app/build.gradle`, the bug disappears**

**Platform**
- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop (Go)

**Platform OS version**
Android 11 (OnePlus)

**How are you picking?**
`FilePicker.platform.getDirectoryPath()` in the example app

**Details to reproduce the issue**
- Use Android 11 (maybe only OnePlus is affected)
- Run the example app with `flutter run --release`
- Try to pick a directory using the "Pick folder" button in the example app

**Flutter Version details**
```
[✓] Flutter (Channel stable, 2.2.2, on Linux, locale de_DE.UTF-8)
    • Flutter version 2.2.2 at /home/redsolver/dev/flutter
    • Framework revision d79295af24 (vor 3 Tagen), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/redsolver/Android/Sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Connected device (3 available)
    • GM1913 (mobile) • <removed id> • android-arm64  • Android 11 (API 30)
    ```

### PR DESCRIPTION
**Pull request by tomm1e**
Fixes #745

### CODE REVIEW

**Comment by miguelpruivo** [comment]
This doesn't seem to solve when folders are inside `Downloads` directory, for example.

**Comment by tomm1e** [comment]
I tested it on 11 emulator and 11 device they both return full paths for folders inside Download.

Untitled

Uninstall any old versions on the device and try a clean build off my fork with a new folder in Download.

**Comment by fsonntag** [comment]
I tested it for folders inside and outside of `Downloads` and it fixes the issue!

Tested on a Google Pixel 4a.

**Comment by miguelpruivo** [comment]
I’ll have to give it a try next week before merging. Thank you.

**Comment by tomm1e** [comment]
@miguelpruivo I added the fallback for earlier versions. Tested 11 and 10 emulator both work now.

**Comment by miguelpruivo** [comment]
@tomm1e thank you. I'll give it a try tomorrow.

**Comment by miguelpruivo** [comment]
https://user-images.githubusercontent.com/27860743/127021274-b437cfdd-1611-4835-92cd-f9dbaf748370.mov

On SDK 29 it's not working, however, on SDK 30 it seems to be. Can you take a look why @tomm1e?

**Comment by tomm1e** [comment]
@miguelpruivo Added another fix for the Download folder on 29. Because of SAF, the Uri has a different type of document id depending on the situation.

**Comment by miguelpruivo** [comment]
Ok, seems to be working now! Thank you.

**Comment by miguelpruivo** [comment]
Published with 3.0.4. 🎉

**Comment by ujwalbasnet1** [comment]
got the issue on `file_picker: ^5.2.10`
android 12, GM1913, OnePlus 7T
image
FileSystemException: Directory listing failed, path = '/' (OS Error: Permission denied, errno = 13)

**Pull request merged**
