### PR TITLE
Added kdialog arguments

### PR DESCRIPTION
**Pull request by mnipritom**
This should cover all FilePicker functionalities for KDE Plasma distributions, as KDE Plasma ships with `kdialog` for scripting based operations. Even though `qarma` is Qt implementation of `zenity`, I could not find any KDE Plasma distro that is still utilizing `qarma` for file system manipulations.

Please note: I have found that, `kdialog` is not correctly handling file filter MIME types, where it **CAN** accept filters as String (eg : `'*.ogg *.mp4'` etc), but does not filter them unless addressing MIME types in `'video/ogg video/mp4'` this format. I will be filing a bug on KDE gitlab addressing this issue. So I did not change anything regarding file filter types.

I am trying to achieve `kdialog` functionalities with minimal changes and being new to software development, am willing to hear any feedback you guys have to say. 

Thanks you for the package and please accept my contribution.

### CODE REVIEW

**Comment by mnipritom** [comment]
https://user-images.githubusercontent.com/10971185/148632475-e864607a-89ff-41f5-be2f-c55aee834484.mp4

**Review by miguelpruivo — APPROVED** [review]
LGTM

**Comment by miguelpruivo** [comment]
Hi, do you mind creating a PR again with this but also adding the changelog and bumping to 4.3.1 version? Thanks.

**Comment by mnipritom** [comment]
Sure thing

**Pull request merged**
